package com.siriusgg.oot.model.places;

public enum Overworld {
    KOKIRI_FOREST,
    LOST_WOODS,
    HYRULE_FIELD,
    MARKET_ENTRANCE,
    MARKET,
    TOT_ENTRANCE,
    HYRULE_CASTLE,
    LON_LON_RANCH,
    KAKARIKO_VILLAGE,
    GRAVEYARD,
    DEATH_MOUNTAIN_TRAIL,
    SACRED_FOREST_MEADOW,
    GORON_CITY,
    DEATH_MOUNTAIN_CRATER,
    ZORAS_RIVER,
    ZORAS_DOMAIN,
    LAKE_HYLIA,
    ZORAS_FOUNTAIN,
    GERUDO_VALLEY,
    GERUDOS_FORTRESS,
    HAUNTED_WASTELAND,
    DESERT_COLOSSUS
}
