package com.siriusgg.oot.model.places;

public class TransitionNames {
    public static String toNiceString(final String internalName) {
        switch(internalName) {
            case "BottomOfTheWellToKakariko": return "Bottom of the Well to Kakariko";
            case "DampesGraveToGraveyard": return "Dampe's Grave to Graveyard";
            case "DampesGraveToWindmill": return "Dampe's Grave to Windmill";
            case "DMCToGreatFairy": return "Death Mountain Crater to DMC Great Fairy";
            case "DMCToFireTemple": return "Death Mountain Crater to Fire Temple";
            case "DMCToDMCUpperGrotto": return "Death Mountain Crater to DMC Upper Grotto";
            case "DMCToDMCHammerGrotto": return "Death Mountain Crater to DMC Hammer Grotto";
            case "DMCToDMT": return "Death Mountain Crater to Death Mountain Trail";
            case "DMCToGoronCity": return "Death Mountain Crater to Goron City";
            case "DMTToGreatFairy": return "Death Mountain Trail to DMT Great Fairy";
            case "DMTToDodongosCavern": return "Death Mountain Trail to Dodongo's Cavern";
            case "DMTToCowGrotto": return "Death Mountain Trail to DMT Cow Grotto";
            case "DMTToStormsGrotto": return "Death Mountain Trail to DMT Storms Grotto";
            case "DMTToKakarikoVillage": return "Death Mountain Trail to Kakariko Village";
            case "DMTToGoronCity": return "Death Mountain Trail to Goron City";
            case "DMTToDMC": return "Death Mountain Trail to Death Mountain Crater";
            case "DMTOwl": return "Death Mountain Trail to Kakariko Village Impa's Roof";
            case "DesertColossusToGreatFairy": return "Desert Colossus to Colossus Great Fairy";
            case "DesertColossusToSpiritTemple": return "Desert Colossus to Spirit Temple";
            case "DesertColossusToColossusGrotto": return "Desert Colossus to Colossus Grotto";
            case "DesertColossusToHauntedWasteland": return "Desert Colossus to Haunted Wasteland";
            case "DesertColossusToSpiritTempleLeftHand": return "Desert Colossus to Spirit Temple Left Hand";
            case "DesertColossusToSpiritTempleRightHand": return "Desert Colossus to Spirit Temple Right Hand";
            case "DodongosCavernToDMT": return "Dodongo's Cavern to Death Mountain Trail";
            // ToDo
            case "FireTempleToDMC": return "";
            case "ForestTempleToSFM": return "";
            case "GerudosFortressToGerudoTrainingGround": return "";
            case "GerudosFortressToStormsGrotto": return "";
            case "GerudosFortressToGerudoValley": return "";
            case "GerudosFortressToHauntedWasteland": return "";
            case "GerudoTrainingGroundToGerudosFortress": return "";
            case "GerudoValleyToCarpenterTent": return "";
            case "GerudoValleyToOctorokGrotto": return "";
            case "GerudoValleyToStormsGrotto": return "";
            case "GerudoValleyToHyruleField": return "";
            case "GerudoValleyToGerudosFortress": return "";
            case "GerudoValleyToLakeHylia": return "";
            case "GoronCityToGoronShop": return "";
            case "GoronCityToGoronGrotto": return "";
            case "GoronCityToDMT": return "";
            case "GoronCityToLostWoods": return "";
            case "GoronCityToDMC": return "";
            case "GraveyardToDampesHouse": return "";
            case "GraveyardToShadowTemple": return "";
            case "GraveyardToShieldGrave": return "";
            case "GraveyardToHeartPieceGrave": return "";
            case "GraveyardToRoyalFamilyTomb": return "";
            case "GraveyardToDampesGrave": return "";
            case "GraveyardToKakarikoVillage": return "";
            case "HauntedWastelandToGerudosFortress": return "";
            case "HauntedWastelandToDesertColossus": return "";
            case "HCToHCGreatFairy": return "";
            case "OGCToOGCGreatFairy": return "";
            case "OGCToInsideGanonsCastle": return "";
            case "HCToStormsGrotto": return "";
            case "HCToMarket": return "";
            case "HCToCastleGarden": return "";
            case "HyruleFieldToHFSouthEastGrotto": return "";
            case "HyruleFieldToHFOpenGrotto": return "";
            case "HyruleFieldToHFInsideFenceGrotto": return "";
            case "HyruleFieldToHFCowGrotto": return "";
            case "HyruleFieldToHFNearMarketGrotto": return "";
            case "HyruleFieldToHFFairyGrotto": return "";
            case "HyruleFieldToHFNearKakGrotto": return "";
            case "HyruleFieldToHFTektikeGrotto": return "";
            case "HyruleFieldToKokiriForest": return "";
            case "HyruleFieldToLakeHylia": return "";
            case "HyruleFieldToGerudoValley": return "";
            case "HyruleFieldToMarketEntrance": return "";
            case "HyruleFieldToKakarikoVillage": return "";
            case "HyruleFieldToZorasRiver": return "";
            case "HyruleFieldToLonLonRanch": return "";
            case "HyruleFieldOwlLanding": return "";
            case "IceCavernToZorasFountain": return "";
            case "InsideGanonsCastleToHyruleCastle": return "";
            case "InsideJabuJabusBellyToZorasFountain": return "";
            case "InsideTheDekuTreeToKokiriForest": return "";
            case "KakarikoPotionShopToFront": return "Kakariko Potion Shop to Kakariko Magic Potion Shop Front";
            case "KakarikoPotionShopToBack": return "Kakariko Potion Shop to Kakariko Magic Potion Shop Back";
            case "KakarikoVillageToCarpenterBossHouse": return "";
            case "KakarikoVillageToHouseOfSkulltula": return "";
            case "KakarikoVillageToImpasHouseFront": return "";
            case "KakarikoVillageToWindmill": return "";
            case "KakarikoVillageToBazaar": return "";
            case "KakarikoVillageToShootingGallery": return "";
            case "KakarikoVillageToPotionShopFront": return "";
            case "KakarikoVillageToOddMedicineBuilding": return "";
            case "KakarikoVillageToPotionShopBack": return "";
            case "KakarikoVillageToImpasHouseBack": return "";
            case "KakarikoVillageToBottomOfTheWell": return "";
            case "KakarikoVillageToRedeadGrotto": return "";
            case "KakarikoVillageToOpenGrotto": return "";
            case "KakarikoVillageToHyruleField": return "";
            case "KakarikoVillageToGraveyard": return "";
            case "KakarikoVillageToDeathMountainTrail": return "";
            case "KakarikoVillageOwlLanding": return "";
            case "KokiriForestToLinksHouse": return "";
            case "KokiriForestToMidosHouse": return "";
            case "KokiriForestToSariasHouse": return "";
            case "KokiriForestToHouseOfTwins": return "";
            case "KokiriForestToKnowItAllHouse": return "";
            case "KokiriForestToKokiriShop": return "";
            case "KokiriForestToInsideTheDekuTree": return "";
            case "KokiriForestToStormsGrotto": return "";
            case "KokiriForestUpperToLostWoodsMain": return "";
            case "KokiriForestMainToLostWoodsBridge": return "";
            case "LakeHyliaToFishingHole": return "";
            case "LakeHyliaToLab": return "";
            case "LakeHyliaToWaterTemple": return "";
            case "LakeHyliaToGrotto": return "";
            case "LakeHyliaToHyruleField": return "";
            case "LakeHyliaOwlStart": return "";
            case "LinksHouseToKokiriForest": return "";
            case "LonLonRanchToTalonsHouse": return "";
            case "LonLonRanchToStable": return "";
            case "LonLonRanchToTower": return "";
            case "LonLonRanchToGrotto": return "";
            case "LonLonRanchToHyruleField": return "";
            case "LostWoodsToNearShortcutsGrotto": return "";
            case "LostWoodsToDekuTheater": return "";
            case "LostWoodsToScrubsGrotto": return "";
            case "LostWoodsToKokiriForestUpper": return "";
            case "LostWoodsToKokiriForestBridge": return "";
            case "LostWoodsToHyruleField": return "";
            case "LostWoodsToGoronCity": return "";
            case "LostWoodsToZorasRiver": return "";
            case "LostWoodsToSacredForestMeadow": return "";
            case "MarketToTreasureChestGame": return "";
            case "MarketToBombchuShop": return "";
            case "MarketToDogLadyHouse": return "";
            case "MarketToManInGreenHouse": return "";
            case "MarketToBombchuBowling": return "";
            case "MarketToShootingGallery": return "";
            case "MarketToMaskShop": return "";
            case "MarketToPotionShop": return "";
            case "MarketToBazaar": return "";
            case "MarketToMarketEntrance": return "";
            case "MarketToToTEntrance": return "";
            case "MarketToHyruleCastle": return "";
            case "MarketEntranceToGuardHouse": return "";
            case "MarketEntranceToHyruleField": return "";
            case "MarketEntranceToMarket": return "";
            case "SacredForestMeadowToForestTemple": return "";
            case "SacredForestMeadowToWolfosGrotto": return "";
            case "SacredForestMeadowToFairyGrotto": return "";
            case "SacredForestMeadowToStormsGrotto": return "";
            case "SacredForestMeadowToLostWoods": return "";
            case "ShadowTempleToGraveyard": return "";
            case "SpiritTempleToDesertColossus": return "";
            case "SpiritTempleLeftHandToDesertColossus": return "";
            case "SpiritTempleRightHandToDesertColossus": return "";
            case "TempleOfTimeToToTEntrance": return "";
            case "TempleOfTimeEntranceToTempleOfTime": return "";
            case "TempleOfTimeEntranceToMarket": return "";
            case "ThievesHideoutBToGerudosFortress": return "";
            case "ThievesHideoutCToGerudosFortress": return "";
            case "ThievesHideoutDToGerudosFortress": return "";
            case "ThievesHideoutEToGerudosFortress": return "";
            case "ThievesHideoutFToGerudosFortress": return "";
            case "ThievesHideoutGToGerudosFortress": return "";
            case "ThievesHideoutHToGerudosFortress": return "";
            case "ThievesHideoutIToGerudosFortress": return "";
            case "ThievesHideoutJToGerudosFortress": return "";
            case "ThievesHideoutKToGerudosFortress": return "";
            case "ThievesHideoutLToGerudosFortress": return "";
            case "ThievesHideoutMToGerudosFortress": return "";
            case "ThievesHideoutNToGerudosFortress": return "";
            case "GerudosFortressToThievesHideoutB": return "";
            case "GerudosFortressToThievesHideoutC": return "";
            case "GerudosFortressToThievesHideoutD": return "";
            case "GerudosFortressToThievesHideoutE": return "";
            case "GerudosFortressToThievesHideoutF": return "";
            case "GerudosFortressToThievesHideoutG": return "";
            case "GerudosFortressToThievesHideoutH": return "";
            case "GerudosFortressToThievesHideoutI": return "";
            case "GerudosFortressToThievesHideoutJ": return "";
            case "GerudosFortressToThievesHideoutK": return "";
            case "GerudosFortressToThievesHideoutL": return "";
            case "GerudosFortressToThievesHideoutM": return "";
            case "GerudosFortressToThievesHideoutN": return "";
            case "WaterTempleToLakeHylia": return "";
            case "WindmillToKakariko": return "";
            case "ZorasDomainToZoraShop": return "";
            case "ZorasDomainToStormsGrotto": return "";
            case "ZorasDomainToZorasRiver": return "";
            case "ZorasDomainToLakeHylia": return "";
            case "ZorasDomainToZorasFountain": return "";
            case "ZorasFountainToGreatFairy": return "";
            case "ZorasFountainToInsideJabuJabusBelly": return "";
            case "ZorasFountainToIceCavern": return "";
            case "ZorasFountainToZorasDomain": return "";
            case "ZorasRiverToOpenGrotto": return "";
            case "ZorasRiverToFairyGrotto": return "";
            case "ZorasRiverToStormsGrotto": return "";
            case "ZorasRiverToHyruleField": return "";
            case "ZorasRiverToZorasDomain": return "";
            case "ZorasRiverToLostWoods": return "";
            default: throw new IllegalArgumentException(internalName);
        }
    }

    public static String getOriginalStart(final String niceName) {
        String[] splitName = niceName.split(" to ");
        if (splitName.length != 2) throw new IllegalStateException("Nice name had multiple instances of string ' to '.");
        return splitName[0];
    }

    public static String getOriginalDestination(final String niceName) {
        String[] splitName = niceName.split(" to ");
        if (splitName.length != 2) throw new IllegalStateException("Nice name had multiple instances of string ' to '.");
        return splitName[1];
    }
}
