package com.siriusgg.oot.model.places;

public enum UnchangingTransition {
    DAMPES_GRAVE_TO_WINDMILL,
    COLOSSUS_TO_SPIRIT_TEMPLE_LEFT_HAND,
    COLOSSUS_TO_SPIRIT_TEMPLE_RIGHT_HAND,
    GERUDO_VALLEY_TO_LAKE_HYLIA,
    SPIRIT_TEMPLE_LEFT_HAND_TO_COLOSSUS,
    SPIRIT_TEMPLE_RIGHT_HAND_TO_COLOSSUS
}
