package com.siriusgg.oot.model.teststuff;

import com.siriusgg.oot.controller.CurrentLocationController;
import com.siriusgg.oot.model.Settings;
import com.siriusgg.oot.model.places.Perspective;
import com.siriusgg.oot.model.places.exitmaps.*;
import com.siriusgg.oot.model.time.Time;

public class OpenAllMaps {
    public static void openAllMaps() {
        Settings settings = new Settings(Time.getInstance(), Perspective.SIDE);
        CurrentLocationController clcBottomOfTheWell = new CurrentLocationController(new BottomOfTheWell(settings));
        clcBottomOfTheWell.init();
        CurrentLocationController clcDampesGrave = new CurrentLocationController(new DampesGrave(settings));
        clcDampesGrave.init();
        CurrentLocationController clcDeathMountainCrater = new CurrentLocationController(new DeathMountainCrater(settings));
        clcDeathMountainCrater.init();
        CurrentLocationController clcDeathMountainTrail = new CurrentLocationController(new DeathMountainTrail(settings));
        clcDeathMountainTrail.init();
        CurrentLocationController clcDesertColossus = new CurrentLocationController(new DesertColossus(settings));
        clcDesertColossus.init();
        CurrentLocationController clcDodongosCavern = new CurrentLocationController(new DodongosCavern(settings));
        clcDodongosCavern.init();
        CurrentLocationController clcFireTemple = new CurrentLocationController(new FireTemple(settings));
        clcFireTemple.init();
        CurrentLocationController clcForestTemple = new CurrentLocationController(new ForestTemple(settings));
        clcForestTemple.init();
        CurrentLocationController clcGerudosFortress = new CurrentLocationController(new GerudosFortress(settings));
        clcGerudosFortress.init();
        CurrentLocationController clcGerudoTrainingGround = new CurrentLocationController(new GerudoTrainingGround(settings));
        clcGerudoTrainingGround.init();
        CurrentLocationController clcGerudoValley = new CurrentLocationController(new GerudoValley(settings));
        clcGerudoValley.init();
        CurrentLocationController clcGoronCity = new CurrentLocationController(new GoronCity(settings));
        clcGoronCity.init();
        CurrentLocationController clcGraveyard = new CurrentLocationController(new Graveyard(settings));
        clcGraveyard.init();
        CurrentLocationController clcHauntedWasteland = new CurrentLocationController(new HauntedWasteland(settings));
        clcHauntedWasteland.init();
        CurrentLocationController clcHyruleCastle = new CurrentLocationController(new HyruleCastle(settings));
        clcHyruleCastle.init();
        CurrentLocationController clcHyruleField = new CurrentLocationController(new HyruleField(settings));
        clcHyruleField.init();
        CurrentLocationController clcIceCavern = new CurrentLocationController(new IceCavern(settings));
        clcIceCavern.init();
        CurrentLocationController clcInsideGanonsCastle = new CurrentLocationController(new InsideGanonsCastle(settings));
        clcInsideGanonsCastle.init();
        CurrentLocationController clcInsideJabuJabusBelly = new CurrentLocationController(new InsideJabuJabusBelly(settings));
        clcInsideJabuJabusBelly.init();
        CurrentLocationController clcInsideTheDekuTree = new CurrentLocationController(new InsideTheDekuTree(settings));
        clcInsideTheDekuTree.init();
        CurrentLocationController clcKakarikoMagicPotionShop = new CurrentLocationController(new KakarikoMagicPotionShop(settings));
        clcKakarikoMagicPotionShop.init();
        CurrentLocationController clcKakarikoVillage = new CurrentLocationController(new KakarikoVillage(settings));
        clcKakarikoVillage.init();
        CurrentLocationController clcKokiriForest = new CurrentLocationController(new KokiriForest(settings));
        clcKokiriForest.init();
        CurrentLocationController clcLakeHylia = new CurrentLocationController(new LakeHylia(settings));
        clcLakeHylia.init();
        CurrentLocationController clcLinksHouse = new CurrentLocationController(new LinksHouse(settings));
        clcLinksHouse.init();
        CurrentLocationController clcLonLonRanch = new CurrentLocationController(new LonLonRanch(settings));
        clcLonLonRanch.init();
        CurrentLocationController clcLostWoods = new CurrentLocationController(new LostWoods(settings));
        clcLostWoods.init();
        CurrentLocationController clcMarket = new CurrentLocationController(new Market(settings));
        clcMarket.init();
        CurrentLocationController clcMarketEntrance = new CurrentLocationController(new MarketEntrance(settings));
        clcMarketEntrance.init();
        CurrentLocationController clcSacredForestMeadow = new CurrentLocationController(new SacredForestMeadow(settings));
        clcSacredForestMeadow.init();
        CurrentLocationController clcShadowTemple = new CurrentLocationController(new ShadowTemple(settings));
        clcShadowTemple.init();
        CurrentLocationController clcSpiritTemple = new CurrentLocationController(new SpiritTemple(settings));
        clcSpiritTemple.init();
        CurrentLocationController clcTempleOfTime = new CurrentLocationController(new TempleOfTime(settings));
        clcTempleOfTime.init();
        CurrentLocationController clcThievesHideout = new CurrentLocationController(new ThievesHideout(settings));
        clcThievesHideout.init();
        CurrentLocationController clcToTEntrance = new CurrentLocationController(new ToTEntrance(settings));
        clcToTEntrance.init();
        CurrentLocationController clcWaterTemple = new CurrentLocationController(new WaterTemple(settings));
        clcWaterTemple.init();
        CurrentLocationController clcWindmill = new CurrentLocationController(new Windmill(settings));
        clcWindmill.init();
        CurrentLocationController clcZorasDomain = new CurrentLocationController(new ZorasDomain(settings));
        clcZorasDomain.init();
        CurrentLocationController clcZorasFountain = new CurrentLocationController(new ZorasFountain(settings));
        clcZorasFountain.init();
        CurrentLocationController clcZorasRiver = new CurrentLocationController(new ZorasRiver(settings));
        clcZorasRiver.init();
    }
}
